### PR TITLE
v0.6.5

### PR DESCRIPTION
**Pull request by stolarczyk**
todo:
- [x] changelog
- [x] more tests
- [x] release date

### CODE REVIEW

**Comment by nsheff** [comment]
@michalstolarczyk can you confirm that the refgenieserver smoketests works with this update?

https://github.com/databio/refgenieserver/blob/master/test_refgenie.sh

**Review by nsheff — APPROVED** [review]
This is working for me on bulker. looks great!

**Comment by stolarczyk** [comment]
> @michalstolarczyk can you confirm that the refgenieserver smoketests works with this update?
> 
> https://github.com/databio/refgenieserver/blob/master/test_refgenie.sh

can confirm, after some updates to the tests

**Comment by nsheff** [comment]
maybe we should double-check that looper/divvy are still working? then let's go ahead and release. bulker was fine.

**Pull request merged**
